"""Render a finished demo MP4 (no screen recording): for each play, composite the
clip (left) with a panel (right) showing the CV input + the REAL Gemini play-by-play
and provenance (model / elapsed / tokens), then stitch into one reel.

  python compose_demo.py --plays <id1>,<id2>
  python compose_demo.py --game 26bb5808-... --limit 4
  python compose_demo.py --plays <id> --out demo_out/play1.mp4
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, str(Path(__file__).resolve().parent))
from app import clips, gemini, supabase_client as sb  # noqa: E402

W, H = 1920, 1080
PANEL_W = 540
VIDEO_W = W - PANEL_W
PAD = 32
OUT_DIR = Path(__file__).resolve().parent / "demo_out"

BG = (10, 14, 20)
CARD = (20, 26, 36)
TEXT = (226, 232, 240)
MUTED = (120, 130, 145)
BRAND = (129, 158, 255)
ACCENT = (245, 158, 66)
GREEN = (52, 211, 153)
AMBER = (251, 191, 36)

_F = "/System/Library/Fonts/Supplemental/Arial.ttf"
_FB = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
_FM = "/System/Library/Fonts/Menlo.ttc"


def font(path: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(path, size)


def wrap(draw, text: str, fnt, max_w: int) -> list[str]:
    out, line = [], ""
    for word in text.split():
        trial = f"{line} {word}".strip()
        if draw.textlength(trial, font=fnt) <= max_w:
            line = trial
        else:
            if line:
                out.append(line)
            line = word
    if line:
        out.append(line)
    return out or [""]


def class_color(label: str) -> tuple:
    u = label.upper()
    if "MAKE" in u:
        return GREEN
    if "MISS" in u or "TURNOVER" in u or "TOV" in u:
        return AMBER
    return BRAND


def events_summary(events) -> str:
    if not isinstance(events, list):
        return ""
    parts = []
    for e in events:
        if isinstance(e, dict):
            parts.append(" · ".join(str(x) for x in (e.get("label"), e.get("playerA")) if x))
    return "   |   ".join(parts)


_TAG_SKIP = {"", "none", "unknown", "n/a"}


def line_tags(ln) -> str:
    vals = [
        ln.shot_type, ln.shot_qualifier,
        f"{ln.shooting_hand} hand" if ln.shooting_hand not in _TAG_SKIP else "",
        ln.court_location, ln.contest, ln.outcome,
    ]
    return "   ·   ".join(
        str(v).replace("-", " ").replace("_", " ")
        for v in vals if str(v).lower().strip() not in _TAG_SKIP
    )


def render_panel(play: dict, vmeta: dict, res, elapsed: float, png: Path) -> None:
    img = Image.new("RGB", (PANEL_W, H), BG)
    d = ImageDraw.Draw(img)
    x = PAD
    maxw = PANEL_W - 2 * PAD
    y = PAD

    f_title = font(_FB, 24)
    f_h = font(_FB, 17)
    f_b = font(_F, 16)
    f_s = font(_F, 13)
    f_m = font(_FM, 13)
    f_desc = font(_F, 16)
    f_tag = font(_FB, 13)

    # header: logo + title
    d.rounded_rectangle([x, y, x + 34, y + 34], radius=8, fill=ACCENT)
    d.text((x + 9, y + 5), "u", font=f_title, fill=(255, 255, 255))
    d.text((x + 46, y + 2), "uball", font=f_title, fill=TEXT)
    d.text((x + 46, y + 30), "VLM Play-by-Play", font=f_s, fill=MUTED)
    y += 58
    d.line([x, y, x + maxw, y], fill=CARD, width=2)
    y += 18

    # classification + angle
    cc = class_color(play["classification"])
    d.text((x, y), play["classification"] or "PLAY", font=f_h, fill=cc)
    d.text((x + d.textlength(play["classification"] or "PLAY", font=f_h) + 12, y + 1),
           f"{vmeta.get('kind','')}/{play.get('angle','')}", font=f_s, fill=MUTED)
    y += 30

    # CV input
    cv = events_summary(play.get("events"))
    if cv:
        d.text((x, y), "CV INPUT (Supabase)", font=f_tag, fill=MUTED)
        y += 20
        for ln in wrap(d, cv, f_s, maxw):
            d.text((x, y), ln, font=f_s, fill=(170, 180, 195))
            y += 18
        y += 8

    # provenance
    badge = "✓ Generated by Google Gemini"
    d.rounded_rectangle([x, y, x + d.textlength(badge, font=f_tag) + 18, y + 26],
                        radius=6, fill=(16, 50, 38))
    d.text((x + 9, y + 5), badge, font=f_tag, fill=GREEN)
    y += 34
    tokens = (res.usage or {}).get("total_tokens")
    prov = f"{res.model}   ·   {elapsed:.1f}s   ·   {tokens:,} tokens" if tokens else f"{res.model}   ·   {elapsed:.1f}s"
    d.text((x, y), prov, font=f_m, fill=(150, 160, 175))
    y += 30
    d.line([x, y, x + maxw, y], fill=CARD, width=2)
    y += 16

    # summary
    if res.narration.summary:
        for ln in wrap(d, res.narration.summary, f_b, maxw):
            d.text((x, y), ln, font=f_b, fill=TEXT)
            y += 22
        y += 10

    # play-by-play lines
    d.text((x, y), "PLAY-BY-PLAY", font=f_tag, fill=MUTED)
    y += 24
    for i, ln in enumerate(res.narration.play_by_play, 1):
        if y > H - 80:
            break
        for j, seg in enumerate(wrap(d, f"{i}. {ln.description}", f_desc, maxw)):
            d.text((x, y), seg, font=f_desc, fill=TEXT)
            y += 21
        tags = line_tags(ln)
        if tags:
            for seg in wrap(d, tags, f_tag, maxw):
                d.text((x, y), seg, font=f_tag, fill=BRAND)
                y += 18
        y += 10

    img.save(png)


def clip_duration(path: Path) -> float:
    p = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of",
         "default=nw=1:nk=1", str(path)], capture_output=True, text=True)
    try:
        return float(p.stdout.strip())
    except ValueError:
        return 8.0


def compose_segment(clip: Path, panel: Path, out: Path, dur: float) -> None:
    fc = (
        f"[0:v]scale={VIDEO_W}:{H}:force_original_aspect_ratio=decrease,"
        f"pad={VIDEO_W}:{H}:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1,fps=30[v];"
        f"[v][1:v]hstack=inputs=2,format=yuv420p[out]"
    )
    cmd = ["ffmpeg", "-nostdin", "-y", "-i", str(clip), "-loop", "1", "-i", str(panel),
           "-filter_complex", fc, "-map", "[out]", "-t", f"{dur:.2f}",
           "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
           "-r", "30", "-an", str(out)]
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0 or not out.exists():
        raise RuntimeError(f"segment ffmpeg failed:\n{p.stderr[-1500:]}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--plays", default="")
    ap.add_argument("--game", default="")
    ap.add_argument("--limit", type=int, default=4)
    ap.add_argument("--model", default="flash")
    ap.add_argument("--out", default=str(OUT_DIR / "reel.mp4"))
    args = ap.parse_args()

    if args.plays.strip():
        play_ids = [p.strip() for p in args.plays.split(",") if p.strip()]
    elif args.game:
        play_ids = [p["play_id"] for p in sb.list_plays(args.game)[: args.limit]]
    else:
        print("provide --plays or --game"); return 2

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    segments: list[Path] = []
    for n, pid in enumerate(play_ids, 1):
        play = sb.get_play(pid)
        vmeta = sb.video_meta(play["game_id"], play["angle"])
        t0, t1 = sb.clip_window(play, vmeta)
        print(f"[{n}/{len(play_ids)}] {play['classification']} {vmeta['kind']}/{play['angle']} — slicing…", flush=True)
        clip = clips.extract_clip(vmeta["s3_key"], t0, t1)
        print(f"    narrating with Gemini ({args.model})…", flush=True)
        ts = time.time()
        res = gemini.narrate_clip(str(clip), model=args.model,
                                  events=play.get("events"), context=sb.game_context(play["game_id"]))
        elapsed = time.time() - ts
        tok = (res.usage or {}).get("total_tokens")
        print(f"    ✓ {elapsed:.1f}s · {tok} tokens · {res.narration.summary[:60]}", flush=True)
        panel = OUT_DIR / f"_panel_{n}.png"
        render_panel(play, vmeta, res, elapsed, panel)
        seg = OUT_DIR / f"_seg_{n}.mp4"
        compose_segment(clip, panel, seg, clip_duration(clip))
        segments.append(seg)

    # concat
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    if len(segments) == 1:
        out.write_bytes(segments[0].read_bytes())
    else:
        listf = OUT_DIR / "_concat.txt"
        listf.write_text("".join(f"file '{s.resolve()}'\n" for s in segments))
        p = subprocess.run(["ffmpeg", "-nostdin", "-y", "-f", "concat", "-safe", "0",
                            "-i", str(listf), "-c", "copy", str(out)],
                           capture_output=True, text=True)
        if p.returncode != 0:
            raise RuntimeError(f"concat failed:\n{p.stderr[-1500:]}")
    print(f"\nDONE -> {out}  ({out.stat().st_size/1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
